### ISSUE TITLE
Unable to create Jar file - enable logging to csv file

### ISSUE THREAD

**Issue by Novshathaleem** [i2group/analyze#62]
We tried to create a jar file out of the sdk projects from the git, however we are unable to create a jar file.
The same steps given in the documents were followed but when I try to create a Jar file, getting "ClassPath not found" error
Will you please help us in compiled code.

**Comment by Novshathaleem** [comment]
We are upgrading from i2Analyze 4.3.0 to 4.3.4, application started with 4.3.4 however we are facing issues with CSV logging, then we downloaded the projects from the git and tried to make jar out of that, considering the existing jar file might be incompatible with new i2analyze 4.3.4. 
Unfortunately unable to create a jar file because there are some errors in the code. Will you please assist us here

OS:
Linux  3.10.0-1160.36.2.el7.x86_64 #1 SMP Thu Jul 8 02:53:40 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Tried creating jar in Eclipse

**Comment by Ricardo-Antunes-i2** [comment]
Hi @Novshathaleem apologies for the late reply.

It would be very helpful if you could you provide us with a stacktrace of the errors you are getting.

**Comment by Novshathaleem** [comment]
Hi @Ricardo-Antunes-i2,

Attaching the error for your reference.

![image](https://user-images.githubusercontent.com/98545575/152735085-3d917e87-8060-4457-9b77-8f83f3998611.png)

![image](https://user-images.githubusercontent.com/98545575/152735148-48a79312-c472-452b-b94f-226ddb0eceeb.png)

**Comment by Ricardo-Antunes-i2** [comment]
Hi @Novshathaleem are you running the examples using the main branch from this repo, or have you downloaded the source code from here: https://github.com/i2group/analyze/releases? Running the source code using the main branch will require that you have the latest toolkit installed. To use dev essentials examples compatible with the 4.3.4 toolkit, then I would suggest you download the source code from here: [Developer Essentials for IBM i2 Analyze v4.3.4](https://github.com/i2group/analyze/releases/tag/8.5.1)

Please let us know if this fixes your problem.

**Comment by Novshathaleem** [comment]
Thanks @Ricardo-Antunes-i2 for the reply. Anyways we are upgrading to 4.3.5 now, will you please redirect me to the developer essentials of the same.

**Comment by Novshathaleem** [comment]
Hi @Ricardo-Antunes-i2 ..I tried with the [Developer Essentials for IBM i2 Analyze v4.3.4](https://github.com/i2group/analyze/releases/tag/8.5.1)..however still facing the same issue, I did followed the steps mentioned in the documents.

![image](https://user-images.githubusercontent.com/98545575/152938909-14e2ac1d-61c3-4dae-a7a1-ff41d5d041a4.png)

**Comment by Ricardo-Antunes-i2** [comment]
Could you please look at the list of problems that are being reported by Eclipse, and report them here:
![image](https://user-images.githubusercontent.com/97099182/152969932-693dd704-f53f-4171-a1d4-782e63232549.png)

**Comment by Novshathaleem** [comment]
Below is the problem

![image](https://user-images.githubusercontent.com/98545575/152971700-cebdadbf-f6bc-4a5e-9dba-3f6e1813dfc6.png)

**Comment by Novshathaleem** [comment]
@Ruairi-OShea-i2 .I went through document on preparing the developer essentials. However our toolkit is in linux box. DO you have any documents related to the same

**Comment by Ricardo-Antunes-i2** [comment]
Could you please confirm that you have imported the "i2-analyze-toolkit-libraries" into eclipse successfully. I do not see that project in your "Project Explorer" screen.

**Comment by Novshathaleem** [comment]
![image](https://user-images.githubusercontent.com/98545575/153114155-b9647e64-5652-4210-8642-52310759384f.png)

Please see the above

**Comment by Ricardo-Antunes-i2** [comment]
Hi @Novshathaleem by the errors you are getting it seems like Eclipse isn't able to pick up the libraries it needs from the toolkit. Could you confirm that you have set the TOOLKIT_ROOT correctly? TOOLKIT_ROOT should point to the directory where you have your toolkit installed.

**Comment by Novshathaleem** [comment]
Hi @Ricardo-Antunes-i2 ..Yes I agree.. BTW the toolkit is installed on Linux machine. Hence it becomes difficult to point to the toolkit directory. Is there any instructions to complete the same steps in Linux box?

**Comment by Novshathaleem** [comment]
Hi @Ricardo-Antunes-i2,

Somehow we compiled the jar file and tried using it. But we are facing the issue below.
Do you have any insights

ERROR 2022-02-16 22:28:36,290 - com.i2group.disco.common.rest.interceptors.internal.JSONExceptionMapper -
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) An exception was caught and reported. Message: Failed Resource Type: [SYSTEM_UNINITIALIZED] from the source class [ConfigurableClassList] with additional context [Class Not Found]: Unexpected problem while instantiating extension class 'CSVAuditLogger' specified by parameter named 'AuditLogger' with value 'CSVAuditLogger'.
  at CommonEndpointModule.configure(CommonEndpointModule.java:50)
      \_ installed by: CatalogResourceModule -> OpalRestServiceEndpointModule -> CommonRestServiceEndpointModule -> CommonEndpointModule -> AuditModule

1 error

======================
Full classname legend:
======================
AuditModule:                     "com.i2group.disco.audit.guice.internal.AuditModule"
CSVAuditLogger:                  "com.example.audit.CSVAuditLogger"
CatalogResourceModule:           "com.i2group.disco.catalogservice.guice.internal.CatalogResourceModule"
CommonEndpointModule:            "com.i2group.disco.common.endpoint.guice.internal.CommonEndpointModule"
CommonRestServiceEndpointModule: "com.i2group.disco.common.rest.internal.CommonRestServiceEndpointModule"
ConfigurableClassList:           "com.i2group.apollo.configuration.ConfigurableClassList"
OpalRestServiceEndpointModule:   "com.i2group.disco.common.rest.internal.OpalRestServiceEndpointModule"
========================
End of classname legend:
========================

**Comment by Anthony-Johnson-i2** [comment]
Hi @Novshathaleem,

I just set this up on my local VM  and I can get exactly the same error as you are now seeing if I...

Set  `AuditLogger=CSVAuditLogger`  rather than setting it to be `com.example.audit.CSVAuditLogger` in `configuration\fragments\common\WEB-INF\classes\ApolloServerSettingsMandatory.properties`.

and  either do not get a built jar file  for example `opal-audit-csv-example.jar`  in the correct destination 

`toolkit\configuration\fragments\opal-audit-csv-example\WEB-INF\lib`

 or forget to add the reference 

`  <fragment name="opal-audit-csv-example"/>`

to my topology file as  the documentation describes before I deploy.

So please check that you are using the full  ` AuditLogger=com.example.audit.CSVAuditLogger`  in `configuration\fragments\common\WEB-INF\classes\ApolloServerSettingsMandatory.properties` and that  you have actually created  the jar file here `toolkit\configuration\fragments\opal-audit-csv-example\WEB-INF\lib ` and that your `topology.xml ` has the correct   `<fragment name="opal-audit-csv-example"/>` line added so that we know to include the contents of that fragment folder when we deploy.

I have found that setting the export destination for the jar up  is a little  touchy and doesn't create the jar file unless I have manually browsed and created the lib sub folder myself from this dialog:
 
![image](https://user-images.githubusercontent.com/98407720/154309847-7681d1a8-1a82-4f1f-b75d-db0807823181.png)

 

Cheers

**Comment by Colvin-Cowie-i2** [comment]
I believe this issue has been resolved. Feel free to re-open it if necessary.
