### ISSUE TITLE
Upgrade instructions

### ISSUE THREAD

**Issue by sdorresteijn88** [i2group/analyze#73]
Good afternoon,
 
Please can you add some more details to the upgrade instructions, [https://i2group.github.io/analyze-containers/content/managing_upgrade_env.html](https://securemail.csngroep.nl/fmlurlsvc/?fewReq=:B:JVk/NDM3PyNzODcrNSNsYTg1ND81NCN2bGJrZHFwd2A4PWRjNz0wNGAwYGNnYTNgZjwxNDFhZzcyMjQ0PGAzPGNkNWBjPDZkYCNxODQzPDc3MjQxMjEjdGxhODYyTUdKXTF9NTQzMzM9KDYyTUdKXTA0NTQzMzM9I3dmdXE4dnFgc2BrK2Fqd3dgdnFgbG9rRWFkcWRgfXVgd3Era2kjZjgwNyNtYWk4NQ==&url=https%3a%2f%2furldefense.com%2fv3%2f__https%3a%2f%2fi2group.github.io%2fanalyze-containers%2fcontent%2fmanaging_upgrade_env.html__%3b%21%21HzYX23eHnp2Wbe4%21TZK4FZIRl4OyvBnGYbCRnb-97cZatES5fm9m9KrENBOE4eUWGpCFUq0YwPJzg06tYlOEA1Dzq53DKTOvtqk1HL3Bc785aIuyQg%24)?
  
The prereqs are very clear and straightforward! But Option 1 (and maybe option 2 as well) is not clear. In my opinion the information below must be added.
1.	Where should you run this command? In the analyze-container or in the analyze-container-260? I think in the 260 folder.
2.	When I run the command in the analyze-container-260 I got the error that ‘upgradeDirectory’ is required in the path-configuration.json. I did this by adding the link to my old configuration (analyze-container)

**Comment by Anthony-Johnson-i2** [comment]
Thank you for your request, I will speak to our Information Developers.

**Comment by Matt-Hadfield-i2** [comment]
Hi sdorresteijn88,

Thanks for your comment.

We will make it more clear that the manage-environment command needs to be run from the `analyze-containers-260` directory.

For the second part, did you complete step 8 from the pre-requisites section? This should have added the upgradeDirectory path to that file.

Thanks,
Matt

**Comment by sdorresteijn88** [comment]
Hi Matt,

I did complete also step 8 of the prereqs. I had also some warnings that the current setup wasn't healthy, so I had to redeploy the old container again. Maybe this corrupted the upgradeDirectory path.

**Comment by Anthony-Johnson-i2** [comment]
Hi @sdorresteijn88 

I am just checking to see if you are happy for this issue to be closed now that you have had the earlier response from @Matt-Hadfield-i2  and that you were not awaiting further feedback on this.

Cheers

**Comment by sdorresteijn88** [comment]
Hi Anthony,

Sorry I forgot to close it. I am happy with the support!
