### ISSUE TITLE
Labeling schema update

### ISSUE THREAD

**Issue by sdorresteijn88** [i2group/analyze#75]
Good afternoon,

I changed the charting schema and the labeling schema. The charting schema changes are visible after a deploy, but the labeling schema changes not. Is there a easy way of changing the labeling schema? The instruction below is a bit too rigorous for a minor adjustment (in my opinion).

https://i2group.github.io/analyze-containers/content/walkthroughs/update_schema.html?q=update

**Comment by Anthony-Johnson-i2** [comment]
Hi Steven
What context are you wanting to see the labelling scheme changes in.  Where do you not see it updating the labels, is it in  i2 Notebook  or Analyst's Notebook premium for example.

If it is  for items being returned via i2 Connect then only the first of any labeling schemes defined for use with  a connector would be used.

Cheers

**Comment by sdorresteijn88** [comment]
Hi Anthony,

I changed the labeling schema and expected that the label in the Record Inspector of ANBP 9.4.1 would change, but this doesn't happen.

I tried it mostly with items being returned via i2 Connect indeed. When I get an item from the information store the label is working as expected.

It would be great if by default the schema and charting schema is inherit from i2 Analyze and that you can add specific differences in i2 Connect.

**Comment by Anthony-Johnson-i2** [comment]
Hi Steven
I agree the steps required to update the full  i2 Analyze schema do seem rather heavy handed if you are only altering  the labelling scheme and are not actually changing any of the i2 Analyze schema itself.

@Matt-Hadfield-i2  is there is a shortcut when you know the i2 Analyze schema itself is not changing for updating the labelling scheme in the containerized environment? I expect as the Labelling Scheme does not exist as a separate file in its own right we have to do this in the 'bit too rigorous' way as Steven says and not doing so could just store up  Shema versioning related issues at a later date :-) 


**The interaction between labelling and Charting schemes can also be a bit confusing, this is what my understanding is.**


- If no labelling scheme has been defined in the i2A schema, then the record when viewed in record inspector will get  <No Label> and if there is also no setting in the charting scheme for the label then the chart item label is blank.

- If the user defines labelling schemes in the i2 Analyze Schema then in Analyst's Notebook Premium it will use the default one defined or the first one.

- If labelling schemes are defined specifically for an i2 Connect connector then only the first one defined can be used for that connector.

- Whenever you look at a record in the record inspector (or in a results list) it will always use the schema labelling scheme.

- The charting scheme defines what is set on the chart item on the chart. By default it will use the schema labelling scheme for entities. The same can be done for links.

- In a charting scheme, the user is able to override the default behaviour or provide a per item type override to, for example, make use of different property combinations. For links things can go further as with link labels, you are allowed to specify the type name, or for single/directed links the summarization the link record count, or for single a computed flow value based on the sum of a numeric property on a given link type.



In your other point above, you  say that it would be great by default to be able to inherit from the main i2 Analyze schema and Charting Scheme,  there are multiple ways that you can define your Schema/Charting Scheme and you can also map between different Schemas... How are you currently doing this for your connector?

This link has a lot of information about the different ways you can use schemas  and how to map between them for your records if you are using connector provided specific schemas for example

https://docs.i2group.com/analyze/4.4.2/converting_records_between_types.html

You also do not have to get the schema for your connector from each connector individually via a configured URL, you can share a Gateway schema between multiple connectors or even have multiple gateway schemas  and chose which one each of your connectors uses.

**Comment by sdorresteijn88** [comment]
Hi Anthony,

Thanks for your detailed answer. My question is indeed not clear enough. It's very powerfull that you 'easily' can map entities and attributes from the infostore, the gateway and connectors. But it's hard to allign the representation of the mapped entities/links from multiple sources.

In my opinion it would be nice if the labeling and charting schema has inheritance. When you mapped a connector to the infostore that the labeling schema of the infostore is applied automatically to the entities from the connector. Now you have to edit multiple xml files to ensure all entities and links look consistent in both i2 Notebook and ANBP on the charts.

I also tried to change the charting schema of i2 Notebook. I replaced the 'code' below to all the charting schemas (connector, gateway and infostore), but I didn't get the date/time visible as label.

 
          <ItemType Id="LOB1">
            <PropertyMappings>
              <PropertyMapping Property="Date">
                <ResolvableValue>
                  <ApolloProperty Id="LOB4">
                    <Aggregation Values="AllValuesFromAllItems" Operation="Minimum" />
                  </ApolloProperty>
                </ResolvableValue>
              </PropertyMapping>
              <PropertyMapping Property="Time">
                <ResolvableValue>
                  <ApolloProperty Id="LOB4">
                    <Aggregation Values="AllValuesFromAllItems" Operation="Minimum" />
                  </ApolloProperty>
                </ResolvableValue>
              </PropertyMapping>
            </PropertyMappings>
            <AttributeMappings>
              <AttributeMapping Name="Observation Type">
                <ResolvableValue>
                  <ApolloProperty Id="LOB3">
                    <Aggregation />
                  </ApolloProperty>
                </ResolvableValue>
              </AttributeMapping>
              <AttributeMapping Name="Date and Time">
                <ResolvableValue>
                  <ApolloProperty Id="LOB4">
                    <Aggregation />
                  </ApolloProperty>
                </ResolvableValue>
              </AttributeMapping>
            </AttributeMappings>
          </ItemType>

![image](https://github.com/i2group/analyze/assets/52672945/2de84ce0-8b67-4118-8c91-be2b18ec7541)

**Comment by sdorresteijn88** [comment]
Thank you very much for the feedback!
